#!/usr/bin/env bash
pgrep myscript.pid >/var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
trap 'rm /var/run/myscript.pid; exit' SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
